apiVersion: v1
kind: Namespace
metadata:
  name: development

---

apiVersion: v1
kind: Namespace
metadata:
  name: production

---

# Roles

# DevOps Role 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development
  name: devops-role
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "services", "configmaps", "deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]

---

#  Developer Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
  namespace: development
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "services", "configmaps", "deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
  
---

# Secret Reader ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]

---

# Production DevOps Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prod-devops-role
  namespace: production
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "services", "configmaps", "deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]

---

# Production Developer Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prod-developer-role
  namespace: production
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "services", "configmaps", "deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]

---

# Bindings

# DevOps RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-access
  namespace: development
subjects:
- kind: Group
  name: devops-group
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: ivan.petrov@company.com
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: maria.sidorova@company.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: devops-role
  apiGroup: rbac.authorization.k8s.io

---

# Developer RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-developers-binding
  namespace: development
subjects:
- kind: Group
  name: app-developers
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: alex.ivanov@company.com
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: olga.smirnova@company.com
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: dmitry.kozlov@company.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io

---

# Secret Reader ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-readers-binding
subjects:
- kind: Group
  name: secret-readers
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: security.admin@company.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: secret-reader-role
  apiGroup: rbac.authorization.k8s.io

---

# Production DevOps RoleBinding
aVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-devops-binding
  namespace: production
subjects:
- kind: Group
  name: devops-group
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: ivan.petrov@company.com
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: maria.sidorova@company.com
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: senior.devops@company.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: prod-devops-role
  apiGroup: rbac.authorization.k8s.io

---

# Production Developer RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-developer-binding
  namespace: production
subjects:
- kind: Group
  name: app-developers
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: alex.ivanov@company.com
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: senior.developer@company.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: prod-developer-role
  apiGroup: rbac.authorization.k8s.io
