apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8spsprunasnonroot
spec:
  crd:
    spec:
      names:
        kind: K8sPSPRunAsNonRoot
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8spsprunasnonroot

        violation[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          not has_runasnonroot(container)
          msg := sprintf("Container %v must run as non-root (runAsNonRoot=true required)", [container.name])
        }

        violation[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          container.securityContext.runAsUser == 0
          msg := sprintf("Container %v cannot run as UID 0", [container.name])
        }

        has_runasnonroot(container) {
          container.securityContext.runAsNonRoot == true
        }