apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: host-path
          mountPath: /data
  volumes:
    - name: host-path
      hostPath:
        path: /var/log