apiVersion: v1
kind: Pod
metadata:
  name: secure-pod-2
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      emptyDir: {}