apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPForbidPrivileged
metadata:
  name: psp-forbid-privileged
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "audit-zone"